language: node_js
sudo: false
node_js:
  - 16.17.0
before_install:
  - node -v
  - npm -v
install:
  - npm install
before_script:
script:
  - npm test
jobs:
  include: 
    - stage: "Lint and Format"
      name: "Format"
      script: npm run format
    - name: "Lint"
      script: npm run lint:fix