language: node_js
sudo: false
node_js:
  - 16.17.0
before_install:
  - node -v
  - npm -v
install:
  - npm install
before_script:
script:
  - npm run lint
  - npm run test
  - npm run build
  - if [ $TRAVIS_BRANCH = "main" ] && [ $TRAVIS_PULL_REQUEST = "false" ]; then 
    docker build -t cyrusfurtado/react-app:0.0.1 .; fi
# jobs:
#   include: 
#     - stage: "Lint and Format"
#       name: "Format"
#       script: npm run format
#     - name: "Lint"
#       script: npm run lint:fix